# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import configparser
import os
import sys

from PyQt5 import QtCore, QtWidgets, QtGui
from PyQt5.QtWidgets import QMessageBox

import call_aws


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(883, 630)
        Form.setStyleSheet("background-image: url(:/newPrefix/images/login1.png);")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(620, 310, 190, 32))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(15)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("border-radius:13px")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.setText('Admin')
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(620, 350, 190, 32))
        self.lineEdit_2.setStyleSheet("border-radius:13px")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_2.setFocus()
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(610, 450, 91, 27))
        self.pushButton.setStyleSheet(
            "color:black;color:red;background-color:rgb(180,180,180);border:2px;border-radius:10px;padding:2px 4px;font-size:14pt")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(730, 450, 81, 27))
        self.pushButton_2.setStyleSheet(
            "color:black;color:red;background-color:rgb(180,180,180);border:2px;border-radius:10px;padding:2px 4px;font-size:14pt")
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)

        self.pushButton.clicked.connect(self.word_get)
        self.pushButton.setShortcut("enter")  # 绑定快捷键
        self.pushButton_2.clicked.connect(Form.close)
        self.pushButton_2.setShortcut("esc")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "全自动恒温恒湿称重系统"))
        self.pushButton.setText(_translate("Form", "登录"))
        self.pushButton.setShortcut('enter')
        self.pushButton_2.setText(_translate("Form", "退出"))
        self.pushButton_2.setShortcut('esc')

    def word_get(self):
        login_password = self.lineEdit_2.text()
        BASE_DIR = os.path.dirname(os.path.realpath(sys.argv[0]))
        conf = configparser.RawConfigParser()
        conf.read(os.path.join(BASE_DIR, 'setting_aws.ini'))
        login_conf = conf.get('Login', 'pass_word')
        if login_password == login_conf:
            ui_hello.show()
            Form.close()
        else:
            QMessageBox.warning(Form,
                                "警告",
                                "用户名或密码错误！",
                                QMessageBox.Yes)
            self.lineEdit_2.end(True)  # 定位光标到最右边


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui_hello = call_aws.MyMainWindow()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
