# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tem.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import uuid

from PyQt5 import QtCore, QtGui, QtWidgets

mac = uuid.uuid1()
mac = str(mac)
mac = mac[-12:].upper()
print(str(mac))
if "1063C8E864DA" == str(mac):
    class Ui_Form(object):
        def setupUi(self, Form):
            Form.setObjectName("Form")
            Form.resize(700, 405)
            self.gridLayoutWidget = QtWidgets.QWidget(Form)
            self.gridLayoutWidget.setGeometry(QtCore.QRect(190, 120, 333, 221))
            self.gridLayoutWidget.setObjectName("gridLayoutWidget")
            self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
            self.gridLayout.setContentsMargins(0, 0, 0, 0)
            self.gridLayout.setObjectName("gridLayout")
            self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
            font = QtGui.QFont()
            font.setPointSize(15)
            self.lineEdit.setFont(font)
            self.lineEdit.setObjectName("lineEdit")
            self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
            self.lineEdit_2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
            font = QtGui.QFont()
            font.setPointSize(15)
            self.lineEdit_2.setFont(font)
            self.lineEdit_2.setObjectName("lineEdit_2")
            self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 1)
            self.label = QtWidgets.QLabel(self.gridLayoutWidget)
            font = QtGui.QFont()
            font.setPointSize(15)
            self.label.setFont(font)
            self.label.setObjectName("label")
            self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
            self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
            font = QtGui.QFont()
            font.setPointSize(15)
            self.label_2.setFont(font)
            self.label_2.setObjectName("label_2")
            self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
            self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
            font = QtGui.QFont()
            font.setPointSize(15)
            self.label_3.setFont(font)
            self.label_3.setObjectName("label_3")
            self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
            self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
            font = QtGui.QFont()
            font.setPointSize(15)
            self.label_4.setFont(font)
            self.label_4.setObjectName("label_4")
            self.gridLayout.addWidget(self.label_4, 1, 2, 1, 1)
            self.label_5 = QtWidgets.QLabel(Form)
            self.label_5.setGeometry(QtCore.QRect(250, -20, 291, 171))
            font = QtGui.QFont()
            font.setFamily("隶书")
            font.setPointSize(22)
            self.label_5.setFont(font)
            self.label_5.setObjectName("label_5")

            self.retranslateUi(Form)
            QtCore.QMetaObject.connectSlotsByName(Form)

        def retranslateUi(self, Form):
            _translate = QtCore.QCoreApplication.translate
            Form.setWindowTitle(_translate("Form", "Form"))
            self.label.setText(_translate("Form", "温度"))
            self.label_2.setText(_translate("Form", "湿度"))
            self.label_3.setText(_translate("Form", "℃"))
            self.label_4.setText(_translate("Form", "%RH"))
            self.label_5.setText(_translate("Form", "温湿度显示屏"))


    if __name__ == "__main__":
        import sys

        app = QtWidgets.QApplication(sys.argv)
        Form = QtWidgets.QWidget()
        ui = Ui_Form()
        ui.setupUi(Form)
        Form.show()
        sys.exit(app.exec_())
else:
    print("异常执行")
